---
# This playbook deploys simple applications to JBoss server
- name: Test application 
  hosts: apservers 
#  hosts: localhost 
#  gather_facts: False
  vars_files:
    - roles/vars/main.yml
    - roles/vars/gmail.txt

  roles:
    - smoketest 
