---
# This playbook deploys simple applications to JBoss server
- name: Test application 
  hosts: apservers 
#  hosts: localhost 
#  gather_facts: False
  vars:
    include_vars: 
      file: group_vars/gmail.txt

  roles:
    - smoketest 
